#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Assassination_CharacterMutator

#include "Basic.hpp"

#include "BP_Assassination_CharacterMutator_classes.hpp"
#include "BP_Assassination_CharacterMutator_parameters.hpp"


namespace SDK
{

// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.BuffTimer
// (BlueprintCallable, BlueprintEvent)

void UBP_Assassination_CharacterMutator_C::BuffTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "BuffTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.Debuff
// (BlueprintCallable, BlueprintEvent)

void UBP_Assassination_CharacterMutator_C::Debuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "Debuff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.ExecuteUbergraph_BP_Assassination_CharacterMutator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Assassination_CharacterMutator_C::ExecuteUbergraph_BP_Assassination_CharacterMutator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "ExecuteUbergraph_BP_Assassination_CharacterMutator");

	Params::BP_Assassination_CharacterMutator_C_ExecuteUbergraph_BP_Assassination_CharacterMutator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.GetMutatorDescription_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UBP_Assassination_CharacterMutator_C::GetMutatorDescription_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "GetMutatorDescription_0");

	Params::BP_Assassination_CharacterMutator_C_GetMutatorDescription_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_Assassination_CharacterMutator_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.K2_DeactivateScript
// (Event, Public, BlueprintEvent)

void UBP_Assassination_CharacterMutator_C::K2_DeactivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "K2_DeactivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.OnCombatEntered
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void UBP_Assassination_CharacterMutator_C::OnCombatEntered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "OnCombatEntered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.OnCombatLeft
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void UBP_Assassination_CharacterMutator_C::OnCombatLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "OnCombatLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assassination_CharacterMutator.BP_Assassination_CharacterMutator_C.GetDescription
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UBP_Assassination_CharacterMutator_C::GetDescription() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assassination_CharacterMutator_C", "GetDescription");

	Params::BP_Assassination_CharacterMutator_C_GetDescription Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

