#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BloodPassive6_DoT_StatusEffect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BloodPassive6_DoT_StatusEffect.BP_BloodPassive6_DoT_StatusEffect_C
// 0x0018 (0x04F0 - 0x04D8)
class UBP_BloodPassive6_DoT_StatusEffect_C final : public URStatusEffectAilmentGScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FTimerHandle                           Timer;                                             // 0x04E0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         TickDamage;                                        // 0x04E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BloodPassive6_DoT_StatusEffect(int32 EntryPoint);
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void K2_TickScript(float DeltaTime);
	void TryOverrideTickDamage(double DrainDamage);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BloodPassive6_DoT_StatusEffect_C">();
	}
	static class UBP_BloodPassive6_DoT_StatusEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BloodPassive6_DoT_StatusEffect_C>();
	}
};
static_assert(alignof(UBP_BloodPassive6_DoT_StatusEffect_C) == 0x000008, "Wrong alignment on UBP_BloodPassive6_DoT_StatusEffect_C");
static_assert(sizeof(UBP_BloodPassive6_DoT_StatusEffect_C) == 0x0004F0, "Wrong size on UBP_BloodPassive6_DoT_StatusEffect_C");
static_assert(offsetof(UBP_BloodPassive6_DoT_StatusEffect_C, UberGraphFrame) == 0x0004D8, "Member 'UBP_BloodPassive6_DoT_StatusEffect_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_BloodPassive6_DoT_StatusEffect_C, Timer) == 0x0004E0, "Member 'UBP_BloodPassive6_DoT_StatusEffect_C::Timer' has a wrong offset!");
static_assert(offsetof(UBP_BloodPassive6_DoT_StatusEffect_C, TickDamage) == 0x0004E8, "Member 'UBP_BloodPassive6_DoT_StatusEffect_C::TickDamage' has a wrong offset!");

}

