#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BloodPassive7_StatusEffect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BloodPassive7_StatusEffect.BP_BloodPassive7_StatusEffect_C
// 0x0008 (0x04E0 - 0x04D8)
class UBP_BloodPassive7_StatusEffect_C final : public URStatusEffectAilmentGScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_BloodPassive7_StatusEffect(int32 EntryPoint);
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void OnHealthDepleted_Event(class URHealthComponent* Component, const struct FDamageCombatEvent& DamageEventData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BloodPassive7_StatusEffect_C">();
	}
	static class UBP_BloodPassive7_StatusEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BloodPassive7_StatusEffect_C>();
	}
};
static_assert(alignof(UBP_BloodPassive7_StatusEffect_C) == 0x000008, "Wrong alignment on UBP_BloodPassive7_StatusEffect_C");
static_assert(sizeof(UBP_BloodPassive7_StatusEffect_C) == 0x0004E0, "Wrong size on UBP_BloodPassive7_StatusEffect_C");
static_assert(offsetof(UBP_BloodPassive7_StatusEffect_C, UberGraphFrame) == 0x0004D8, "Member 'UBP_BloodPassive7_StatusEffect_C::UberGraphFrame' has a wrong offset!");

}

