#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BouncyBomb_ProjectileEffect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Niagara_structs.hpp"


namespace SDK::Params
{

// Function BP_BouncyBomb_ProjectileEffect.BP_BouncyBomb_ProjectileEffect_C.ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect
// 0x0348 (0x0348 - 0x0000)
struct BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FHitResult& ImpactResult, const struct FVector& ImpactVelocity)> K2Node_CreateDelegate_OutputDelegate; // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FHitResult>                     K2Node_CustomEvent_HitResults;                     // 0x0028(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	float                                         K2Node_CustomEvent_ActualExplosionRadius;          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const TArray<struct FHitResult>& HitResults, float ActualExplosionRadius)> K2Node_CreateDelegate_OutputDelegate_2; // 0x003C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_real_Variable;                                // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FHitResult>                     Temp_struct_Variable;                              // 0x0050(0x0010)(ReferenceParm, ContainsInstancedReference)
	ENCPoolMethod                                 Temp_byte_Variable;                                // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0063(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ARProjectileBase*                       CallFunc_GetOwningProjectile_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARProjectileBase*                       CallFunc_GetOwningProjectile_ReturnValue_1;        // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FragGrenade_Grenade_C*              K2Node_DynamicCast_AsBP_Frag_Grenade_Grenade;      // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FHitResult& ImpactResult, const struct FVector& ImpactVelocity)> K2Node_CreateDelegate_OutputDelegate_3; // 0x0084(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_CustomEvent_ImpactResult;                   // 0x0098(0x0100)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                K2Node_CustomEvent_ImpactVelocity;                 // 0x0198(0x0018)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B2[0x2];                                      // 0x01B2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BC[0x4];                                      // 0x01BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x01C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0208(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0220(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0230(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0258(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0270(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_K2_GetPlayerController_ReturnValue;       // 0x0288(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAtLocation_ReturnValue;         // 0x0290(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0298(0x0010)(ReferenceParm)
	class ARProjectileBase*                       CallFunc_GetOwningProjectile_ReturnValue_2;        // 0x02A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ENCPoolMethod                                 CallFunc_GetShouldAutoPoolNiagara_ReturnValue;     // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B1[0x3];                                      // 0x02B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetMutableFloatValue_outValue;            // 0x02B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Select_Default;                             // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x02C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D1[0x7];                                      // 0x02D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARGrenade*                              CallFunc_GetOwningGrenade_ReturnValue;             // 0x02D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x02E8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGTask_SpawnExplosion*                 CallFunc_SpawnExplosion_ReturnValue;               // 0x02F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_301[0x7];                                      // 0x0301(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARProjectileBase*                       CallFunc_GetOwningProjectile_ReturnValue_3;        // 0x0308(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARProjectileBase*                       CallFunc_GetOwningProjectile_ReturnValue_4;        // 0x0310(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FragGrenade_Grenade_C*              K2Node_DynamicCast_AsBP_Frag_Grenade_Grenade_1;    // 0x0318(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SpawnExplosion_BaseDamage_ImplicitCast;   // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_334[0x4];                                      // 0x0334(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1;   // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SpawnExplosion_Radius_ImplicitCast;       // 0x0340(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect) == 0x000008, "Wrong alignment on BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect");
static_assert(sizeof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect) == 0x000348, "Wrong size on BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, EntryPoint) == 0x000000, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CustomEvent_HitResults) == 0x000028, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CustomEvent_HitResults' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CustomEvent_ActualExplosionRadius) == 0x000038, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CustomEvent_ActualExplosionRadius' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CreateDelegate_OutputDelegate_2) == 0x00003C, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, Temp_real_Variable) == 0x00004C, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, Temp_struct_Variable) == 0x000050, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, Temp_byte_Variable) == 0x000060, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, Temp_bool_Variable) == 0x000061, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, Temp_bool_Variable_1) == 0x000062, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, Temp_bool_Variable_2) == 0x000063, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetOwningProjectile_ReturnValue) == 0x000068, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetOwningProjectile_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetOwningProjectile_ReturnValue_1) == 0x000070, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetOwningProjectile_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_DynamicCast_AsBP_Frag_Grenade_Grenade) == 0x000078, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_DynamicCast_AsBP_Frag_Grenade_Grenade' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_DynamicCast_bSuccess) == 0x000080, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CreateDelegate_OutputDelegate_3) == 0x000084, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CustomEvent_ImpactResult) == 0x000098, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CustomEvent_ImpactResult' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CustomEvent_ImpactVelocity) == 0x000198, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CustomEvent_ImpactVelocity' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_bBlockingHit) == 0x0001B0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_bInitialOverlap) == 0x0001B1, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_Time) == 0x0001B4, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_Distance) == 0x0001B8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_Location) == 0x0001C0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_ImpactPoint) == 0x0001D8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_Normal) == 0x0001F0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_ImpactNormal) == 0x000208, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_PhysMat) == 0x000220, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_HitActor) == 0x000228, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_HitComponent) == 0x000230, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_HitBoneName) == 0x000238, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_BoneName) == 0x000240, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_HitItem) == 0x000248, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_ElementIndex) == 0x00024C, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_FaceIndex) == 0x000250, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_TraceStart) == 0x000258, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_BreakHitResult_TraceEnd) == 0x000270, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_K2_GetPlayerController_ReturnValue) == 0x000288, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_K2_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_SpawnSoundAtLocation_ReturnValue) == 0x000290, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_SpawnSoundAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_MakeArray_Array) == 0x000298, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetOwningProjectile_ReturnValue_2) == 0x0002A8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetOwningProjectile_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetShouldAutoPoolNiagara_ReturnValue) == 0x0002B0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetShouldAutoPoolNiagara_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetMutableFloatValue_outValue) == 0x0002B4, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetMutableFloatValue_outValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_Select_Default) == 0x0002B8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x0002C0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x0002C8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_Not_PreBool_ReturnValue) == 0x0002D0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetOwningGrenade_ReturnValue) == 0x0002D8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetOwningGrenade_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x0002E0, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_CreateDelegate_OutputDelegate_4) == 0x0002E8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_SpawnExplosion_ReturnValue) == 0x0002F8, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_SpawnExplosion_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_IsValid_ReturnValue) == 0x000300, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetOwningProjectile_ReturnValue_3) == 0x000308, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetOwningProjectile_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_GetOwningProjectile_ReturnValue_4) == 0x000310, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_GetOwningProjectile_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_DynamicCast_AsBP_Frag_Grenade_Grenade_1) == 0x000318, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_DynamicCast_AsBP_Frag_Grenade_Grenade_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, K2Node_DynamicCast_bSuccess_1) == 0x000320, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000328, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_SpawnExplosion_BaseDamage_ImplicitCast) == 0x000330, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_SpawnExplosion_BaseDamage_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1) == 0x000338, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect, CallFunc_SpawnExplosion_Radius_ImplicitCast) == 0x000340, "Member 'BP_BouncyBomb_ProjectileEffect_C_ExecuteUbergraph_BP_BouncyBomb_ProjectileEffect::CallFunc_SpawnExplosion_Radius_ImplicitCast' has a wrong offset!");

// Function BP_BouncyBomb_ProjectileEffect.BP_BouncyBomb_ProjectileEffect_C.OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58
// 0x0018 (0x0018 - 0x0000)
struct BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58 final
{
public:
	TArray<struct FHitResult>                     HitResults;                                        // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	float                                         ActualExplosionRadius;                             // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58) == 0x000008, "Wrong alignment on BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58");
static_assert(sizeof(BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58) == 0x000018, "Wrong size on BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58, HitResults) == 0x000000, "Member 'BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58::HitResults' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58, ActualExplosionRadius) == 0x000010, "Member 'BP_BouncyBomb_ProjectileEffect_C_OnExplosion_64A1F8F54FA4669427FAC0B08BD90F58::ActualExplosionRadius' has a wrong offset!");

// Function BP_BouncyBomb_ProjectileEffect.BP_BouncyBomb_ProjectileEffect_C.OnGrenadeBounce
// 0x0118 (0x0118 - 0x0000)
struct BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0100)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                ImpactVelocity;                                    // 0x0100(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce) == 0x000008, "Wrong alignment on BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce");
static_assert(sizeof(BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce) == 0x000118, "Wrong size on BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce, ImpactResult) == 0x000000, "Member 'BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce::ImpactResult' has a wrong offset!");
static_assert(offsetof(BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce, ImpactVelocity) == 0x000100, "Member 'BP_BouncyBomb_ProjectileEffect_C_OnGrenadeBounce::ImpactVelocity' has a wrong offset!");

}

