#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Blizzard_AreaEffect_Script

#include "Basic.hpp"

#include "BP_Blizzard_AreaEffect_Script_classes.hpp"
#include "BP_Blizzard_AreaEffect_Script_parameters.hpp"


namespace SDK
{

// Function BP_Blizzard_AreaEffect_Script.BP_Blizzard_AreaEffect_Script_C.CheckFrostPassive3
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Multiplier                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Blizzard_AreaEffect_Script_C::CheckFrostPassive3(bool* Result, double* Multiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Blizzard_AreaEffect_Script_C", "CheckFrostPassive3");

	Params::BP_Blizzard_AreaEffect_Script_C_CheckFrostPassive3 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;

	if (Multiplier != nullptr)
		*Multiplier = Parms.Multiplier;
}


// Function BP_Blizzard_AreaEffect_Script.BP_Blizzard_AreaEffect_Script_C.ExecuteUbergraph_BP_Blizzard_AreaEffect_Script
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Blizzard_AreaEffect_Script_C::ExecuteUbergraph_BP_Blizzard_AreaEffect_Script(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Blizzard_AreaEffect_Script_C", "ExecuteUbergraph_BP_Blizzard_AreaEffect_Script");

	Params::BP_Blizzard_AreaEffect_Script_C_ExecuteUbergraph_BP_Blizzard_AreaEffect_Script Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Blizzard_AreaEffect_Script.BP_Blizzard_AreaEffect_Script_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_Blizzard_AreaEffect_Script_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Blizzard_AreaEffect_Script_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Blizzard_AreaEffect_Script.BP_Blizzard_AreaEffect_Script_C.K2_DeactivateScript
// (Event, Public, BlueprintEvent)

void UBP_Blizzard_AreaEffect_Script_C::K2_DeactivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Blizzard_AreaEffect_Script_C", "K2_DeactivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Blizzard_AreaEffect_Script.BP_Blizzard_AreaEffect_Script_C.K2_TickScript
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Blizzard_AreaEffect_Script_C::K2_TickScript(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Blizzard_AreaEffect_Script_C", "K2_TickScript");

	Params::BP_Blizzard_AreaEffect_Script_C_K2_TickScript Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

