#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DungeonGameState

#include "Basic.hpp"

#include "BP_DungeonGameState_classes.hpp"
#include "BP_DungeonGameState_parameters.hpp"


namespace SDK
{

// Function BP_DungeonGameState.BP_DungeonGameState_C.UpdatePlayerCosmetics_Multicast
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARPlayerPawn*                     RPlayerPawn                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FPlayerCosmeticOption&     CosmeticsOptionData                                    (BlueprintVisible, BlueprintReadOnly, Parm)

void ABP_DungeonGameState_C::UpdatePlayerCosmetics_Multicast(class ARPlayerPawn* RPlayerPawn, const struct FPlayerCosmeticOption& CosmeticsOptionData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "UpdatePlayerCosmetics_Multicast");

	Params::BP_DungeonGameState_C_UpdatePlayerCosmetics_Multicast Parms{};

	Parms.RPlayerPawn = RPlayerPawn;
	Parms.CosmeticsOptionData = std::move(CosmeticsOptionData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.UpdatePlayerCosmetics
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARPlayerPawn*                     RPlayerPawn                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FPlayerCosmeticOption&     CosmeticOptionData                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_DungeonGameState_C::UpdatePlayerCosmetics(class ARPlayerPawn* RPlayerPawn, const struct FPlayerCosmeticOption& CosmeticOptionData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "UpdatePlayerCosmetics");

	Params::BP_DungeonGameState_C_UpdatePlayerCosmetics Parms{};

	Parms.RPlayerPawn = RPlayerPawn;
	Parms.CosmeticOptionData = std::move(CosmeticOptionData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.UpdatePlayerClothes_Multicast
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARPlayerPawn*                     PlayerPawn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UStaticMesh*                      NewHeadMesh                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector4&                  Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::UpdatePlayerClothes_Multicast(class ARPlayerPawn* PlayerPawn, class UStaticMesh* NewHeadMesh, const struct FVector4& Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "UpdatePlayerClothes_Multicast");

	Params::BP_DungeonGameState_C_UpdatePlayerClothes_Multicast Parms{};

	Parms.PlayerPawn = PlayerPawn;
	Parms.NewHeadMesh = NewHeadMesh;
	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.UpdatePlayerClothes
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARPlayerPawn*                     RPlayerPawn                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UStaticMesh*                      NewHeadMesh                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector4&                  Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::UpdatePlayerClothes(class ARPlayerPawn* RPlayerPawn, class UStaticMesh* NewHeadMesh, const struct FVector4& Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "UpdatePlayerClothes");

	Params::BP_DungeonGameState_C_UpdatePlayerClothes Parms{};

	Parms.RPlayerPawn = RPlayerPawn;
	Parms.NewHeadMesh = NewHeadMesh;
	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Success_F5C97407439107F5AD7268A51B9F5908
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Success_F5C97407439107F5AD7268A51B9F5908(const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Success_F5C97407439107F5AD7268A51B9F5908");

	Params::BP_DungeonGameState_C_Success_F5C97407439107F5AD7268A51B9F5908 Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Success_760276604B9A33B23DF305B2B3748627
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Success_760276604B9A33B23DF305B2B3748627(const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Success_760276604B9A33B23DF305B2B3748627");

	Params::BP_DungeonGameState_C_Success_760276604B9A33B23DF305B2B3748627 Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Success_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FBlueprintSessionResult&   Result                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_DungeonGameState_C::Success_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC(const class FString& Error, const struct FBlueprintSessionResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Success_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC");

	Params::BP_DungeonGameState_C_Success_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC Parms{};

	Parms.Error = std::move(Error);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Success_373CD0904C4C2D66CF3B3EA1790A81A8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    TravelURL                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Success_373CD0904C4C2D66CF3B3EA1790A81A8(const class FString& TravelURL, const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Success_373CD0904C4C2D66CF3B3EA1790A81A8");

	Params::BP_DungeonGameState_C_Success_373CD0904C4C2D66CF3B3EA1790A81A8 Parms{};

	Parms.TravelURL = std::move(TravelURL);
	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Save Player Stats
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RunFailed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Save_Player_Stats(bool RunFailed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Save Player Stats");

	Params::BP_DungeonGameState_C_Save_Player_Stats Parms{};

	Parms.RunFailed = RunFailed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.RunStarted
// (BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::RunStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "RunStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.RunFinished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RunFailed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::RunFinished(bool RunFailed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "RunFinished");

	Params::BP_DungeonGameState_C_RunFinished Parms{};

	Parms.RunFailed = RunFailed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.RetryPassword
// (BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::RetryPassword()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "RetryPassword");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "ReceiveEndPlay");

	Params::BP_DungeonGameState_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DungeonGameState_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.PushMidRunLoadingScreen
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::PushMidRunLoadingScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "PushMidRunLoadingScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.PushDemoEndScreen_Multicast
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::PushDemoEndScreen_Multicast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "PushDemoEndScreen_Multicast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.PopMidRunLoadingScreen
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::PopMidRunLoadingScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "PopMidRunLoadingScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.PlayerLeft
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::PlayerLeft(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "PlayerLeft");

	Params::BP_DungeonGameState_C_PlayerLeft Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.PlayerJoined
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::PlayerJoined(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "PlayerJoined");

	Params::BP_DungeonGameState_C_PlayerJoined Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.PlayerFinishMidRunLoading
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::PlayerFinishMidRunLoading(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "PlayerFinishMidRunLoading");

	Params::BP_DungeonGameState_C_PlayerFinishMidRunLoading Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnSessionUserInviteAcceptedSteam
// (Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    SessionId                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::OnSessionUserInviteAcceptedSteam(const class FString& SessionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnSessionUserInviteAcceptedSteam");

	Params::BP_DungeonGameState_C_OnSessionUserInviteAcceptedSteam Parms{};

	Parms.SessionId = std::move(SessionId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnSessionUserInviteAcceptedEOS
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FBlueprintSessionResult&   Session                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bWasSuccesful                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::OnSessionUserInviteAcceptedEOS(const struct FBlueprintSessionResult& Session, bool bWasSuccesful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnSessionUserInviteAcceptedEOS");

	Params::BP_DungeonGameState_C_OnSessionUserInviteAcceptedEOS Parms{};

	Parms.Session = std::move(Session);
	Parms.bWasSuccesful = bWasSuccesful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnSegmentStarted_VoiceEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AREnemySpawnAreaSegment*          EnemySpawnAreaSegment                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::OnSegmentStarted_VoiceEvent(class AREnemySpawnAreaSegment* EnemySpawnAreaSegment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnSegmentStarted_VoiceEvent");

	Params::BP_DungeonGameState_C_OnSegmentStarted_VoiceEvent Parms{};

	Parms.EnemySpawnAreaSegment = EnemySpawnAreaSegment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnSegmentCompleted_VoiceEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AREnemySpawnAreaSegment*          EnemySpawnAreaSegment                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::OnSegmentCompleted_VoiceEvent(class AREnemySpawnAreaSegment* EnemySpawnAreaSegment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnSegmentCompleted_VoiceEvent");

	Params::BP_DungeonGameState_C_OnSegmentCompleted_VoiceEvent Parms{};

	Parms.EnemySpawnAreaSegment = EnemySpawnAreaSegment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnSegmentCompleted_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AREnemySpawnAreaSegment*          EnemySpawnAreaSegment                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::OnSegmentCompleted_Event(class AREnemySpawnAreaSegment* EnemySpawnAreaSegment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnSegmentCompleted_Event");

	Params::BP_DungeonGameState_C_OnSegmentCompleted_Event Parms{};

	Parms.EnemySpawnAreaSegment = EnemySpawnAreaSegment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnLevelChanged
// (BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::OnLevelChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnLevelChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnJoinConfirmedSteam
// (BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::OnJoinConfirmedSteam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnJoinConfirmedSteam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnJoinConfirmed
// (BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::OnJoinConfirmed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnJoinConfirmed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnEnemyKilled_VoiceEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARNPCPawnBase*                    EnemyPawn                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::OnEnemyKilled_VoiceEvent(class ARNPCPawnBase* EnemyPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnEnemyKilled_VoiceEvent");

	Params::BP_DungeonGameState_C_OnEnemyKilled_VoiceEvent Parms{};

	Parms.EnemyPawn = EnemyPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.OnCancelJoin
// (BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::OnCancelJoin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "OnCancelJoin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.JoinSession
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBlueprintSessionResult&   Session                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void ABP_DungeonGameState_C::JoinSession(const struct FBlueprintSessionResult& Session)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "JoinSession");

	Params::BP_DungeonGameState_C_JoinSession Parms{};

	Parms.Session = std::move(Session);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.IsDemoEndNode
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::IsDemoEndNode(bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "IsDemoEndNode");

	Params::BP_DungeonGameState_C_IsDemoEndNode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.GetEnterAreaVoicelineEvent
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName*                            EventName                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::GetEnterAreaVoicelineEvent(class FName* EventName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "GetEnterAreaVoicelineEvent");

	Params::BP_DungeonGameState_C_GetEnterAreaVoicelineEvent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EventName != nullptr)
		*EventName = Parms.EventName;
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.FailedToJoinGame
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::FailedToJoinGame(const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "FailedToJoinGame");

	Params::BP_DungeonGameState_C_FailedToJoinGame Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Fail_F5C97407439107F5AD7268A51B9F5908
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Fail_F5C97407439107F5AD7268A51B9F5908(const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Fail_F5C97407439107F5AD7268A51B9F5908");

	Params::BP_DungeonGameState_C_Fail_F5C97407439107F5AD7268A51B9F5908 Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Fail_760276604B9A33B23DF305B2B3748627
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Fail_760276604B9A33B23DF305B2B3748627(const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Fail_760276604B9A33B23DF305B2B3748627");

	Params::BP_DungeonGameState_C_Fail_760276604B9A33B23DF305B2B3748627 Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Fail_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FBlueprintSessionResult&   Result                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_DungeonGameState_C::Fail_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC(const class FString& Error, const struct FBlueprintSessionResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Fail_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC");

	Params::BP_DungeonGameState_C_Fail_6DA6FB9C4A61DB7F7FC3ED9DFDF502AC Parms{};

	Parms.Error = std::move(Error);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.Fail_373CD0904C4C2D66CF3B3EA1790A81A8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    TravelURL                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    Error                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::Fail_373CD0904C4C2D66CF3B3EA1790A81A8(const class FString& TravelURL, const class FString& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "Fail_373CD0904C4C2D66CF3B3EA1790A81A8");

	Params::BP_DungeonGameState_C_Fail_373CD0904C4C2D66CF3B3EA1790A81A8 Parms{};

	Parms.TravelURL = std::move(TravelURL);
	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.ExecuteUbergraph_BP_DungeonGameState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::ExecuteUbergraph_BP_DungeonGameState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "ExecuteUbergraph_BP_DungeonGameState");

	Params::BP_DungeonGameState_C_ExecuteUbergraph_BP_DungeonGameState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.CheckEliteSegment
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AREnemySpawnAreaSegment*          Segment                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsElite                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DungeonGameState_C::CheckEliteSegment(class AREnemySpawnAreaSegment* Segment, bool* IsElite)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "CheckEliteSegment");

	Params::BP_DungeonGameState_C_CheckEliteSegment Parms{};

	Parms.Segment = Segment;

	UObject::ProcessEvent(Func, &Parms);

	if (IsElite != nullptr)
		*IsElite = Parms.IsElite;
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.AutoApplyDifficultyEffects
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_DungeonGameState_C::AutoApplyDifficultyEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "AutoApplyDifficultyEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DungeonGameState.BP_DungeonGameState_C.AcceptEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void ABP_DungeonGameState_C::AcceptEvent(const class FText& Input)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DungeonGameState_C", "AcceptEvent");

	Params::BP_DungeonGameState_C_AcceptEvent Parms{};

	Parms.Input = std::move(Input);

	UObject::ProcessEvent(Func, &Parms);
}

}

