#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FrostPassive5_CharacterMutator

#include "Basic.hpp"

#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FrostPassive5_CharacterMutator.BP_FrostPassive5_CharacterMutator_C
// 0x0000 (0x0108 - 0x0108)
class UBP_FrostPassive5_CharacterMutator_C final : public URGCharacterMutatorScript
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FrostPassive5_CharacterMutator_C">();
	}
	static class UBP_FrostPassive5_CharacterMutator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FrostPassive5_CharacterMutator_C>();
	}
};
static_assert(alignof(UBP_FrostPassive5_CharacterMutator_C) == 0x000008, "Wrong alignment on UBP_FrostPassive5_CharacterMutator_C");
static_assert(sizeof(UBP_FrostPassive5_CharacterMutator_C) == 0x000108, "Wrong size on UBP_FrostPassive5_CharacterMutator_C");

}

