#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Spiritual_CharacterMutator

#include "Basic.hpp"

#include "RGame_structs.hpp"


namespace SDK::Params
{

// Function BP_Spiritual_CharacterMutator.BP_Spiritual_CharacterMutator_C.ExecuteUbergraph_BP_Spiritual_CharacterMutator
// 0x00E8 (0x00E8 - 0x0000)
struct BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_K2_GetPlayerController_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGScriptActorInfo                      CallFunc_K2_GetCurrentActorInfo_ReturnValue;       // 0x0010(0x0030)(ContainsInstancedReference)
	class ARPlayerPawn*                           K2Node_DynamicCast_AsRPlayer_Pawn;                 // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSaveGame*                             CallFunc_GetCurrentSaveGame_ReturnValue;           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0058(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGScriptActorInfo                      CallFunc_K2_GetCurrentActorInfo_ReturnValue_1;     // 0x0068(0x0030)(ContainsInstancedReference)
	class ARPlayerPawn*                           K2Node_DynamicCast_AsRPlayer_Pawn_1;               // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x3];                                       // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00A4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetMutatorRank_ReturnValue;               // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetMutatorValueByVariableName_ReturnValue; // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue_1;                     // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_A_ImplicitCast;     // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator) == 0x000008, "Wrong alignment on BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator");
static_assert(sizeof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator) == 0x0000E8, "Wrong size on BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, EntryPoint) == 0x000000, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_K2_GetPlayerController_ReturnValue) == 0x000008, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_K2_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_K2_GetCurrentActorInfo_ReturnValue) == 0x000010, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_K2_GetCurrentActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, K2Node_DynamicCast_AsRPlayer_Pawn) == 0x000040, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::K2Node_DynamicCast_AsRPlayer_Pawn' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_GetCurrentSaveGame_ReturnValue) == 0x000050, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_GetCurrentSaveGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, K2Node_CreateDelegate_OutputDelegate) == 0x000058, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_K2_GetCurrentActorInfo_ReturnValue_1) == 0x000068, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_K2_GetCurrentActorInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, K2Node_DynamicCast_AsRPlayer_Pawn_1) == 0x000098, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::K2Node_DynamicCast_AsRPlayer_Pawn_1' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, K2Node_DynamicCast_bSuccess_1) == 0x0000A0, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000A4, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_GetMutatorRank_ReturnValue) == 0x0000B4, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_GetMutatorRank_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_GetMutatorValueByVariableName_ReturnValue) == 0x0000B8, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_GetMutatorValueByVariableName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x0000C0, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_FTrunc_ReturnValue) == 0x0000C8, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_Conv_IntToDouble_ReturnValue) == 0x0000D0, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_FTrunc_ReturnValue_1) == 0x0000D8, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_FTrunc_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator, CallFunc_Subtract_DoubleDouble_A_ImplicitCast) == 0x0000E0, "Member 'BP_Spiritual_CharacterMutator_C_ExecuteUbergraph_BP_Spiritual_CharacterMutator::CallFunc_Subtract_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BP_Spiritual_CharacterMutator.BP_Spiritual_CharacterMutator_C.GetDescription
// 0x0010 (0x0010 - 0x0000)
struct BP_Spiritual_CharacterMutator_C_GetDescription final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(BP_Spiritual_CharacterMutator_C_GetDescription) == 0x000008, "Wrong alignment on BP_Spiritual_CharacterMutator_C_GetDescription");
static_assert(sizeof(BP_Spiritual_CharacterMutator_C_GetDescription) == 0x000010, "Wrong size on BP_Spiritual_CharacterMutator_C_GetDescription");
static_assert(offsetof(BP_Spiritual_CharacterMutator_C_GetDescription, ReturnValue) == 0x000000, "Member 'BP_Spiritual_CharacterMutator_C_GetDescription::ReturnValue' has a wrong offset!");

}

