#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TheThrill_StatusEffect

#include "Basic.hpp"

#include "BP_TheThrill_StatusEffect_classes.hpp"
#include "BP_TheThrill_StatusEffect_parameters.hpp"


namespace SDK
{

// Function BP_TheThrill_StatusEffect.BP_TheThrill_StatusEffect_C.ExecuteUbergraph_BP_TheThrill_StatusEffect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TheThrill_StatusEffect_C::ExecuteUbergraph_BP_TheThrill_StatusEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TheThrill_StatusEffect_C", "ExecuteUbergraph_BP_TheThrill_StatusEffect");

	Params::BP_TheThrill_StatusEffect_C_ExecuteUbergraph_BP_TheThrill_StatusEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TheThrill_StatusEffect.BP_TheThrill_StatusEffect_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_TheThrill_StatusEffect_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TheThrill_StatusEffect_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TheThrill_StatusEffect.BP_TheThrill_StatusEffect_C.K2_DeactivateScript
// (Event, Public, BlueprintEvent)

void UBP_TheThrill_StatusEffect_C::K2_DeactivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TheThrill_StatusEffect_C", "K2_DeactivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TheThrill_StatusEffect.BP_TheThrill_StatusEffect_C.RemoveStack
// (Event, Public, BlueprintEvent)

void UBP_TheThrill_StatusEffect_C::RemoveStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TheThrill_StatusEffect_C", "RemoveStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TheThrill_StatusEffect.BP_TheThrill_StatusEffect_C.Stack
// (Event, Public, BlueprintEvent)

void UBP_TheThrill_StatusEffect_C::Stack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TheThrill_StatusEffect_C", "Stack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TheThrill_StatusEffect.BP_TheThrill_StatusEffect_C.UpdateBuffs
// (BlueprintCallable, BlueprintEvent)

void UBP_TheThrill_StatusEffect_C::UpdateBuffs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TheThrill_StatusEffect_C", "UpdateBuffs");

	UObject::ProcessEvent(Func, nullptr);
}

}

