#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UnstablePowerCores_GrenadeScript

#include "Basic.hpp"

#include "BP_UnstablePowerCores_GrenadeScript_classes.hpp"
#include "BP_UnstablePowerCores_GrenadeScript_parameters.hpp"


namespace SDK
{

// Function BP_UnstablePowerCores_GrenadeScript.BP_UnstablePowerCores_GrenadeScript_C.ExecuteUbergraph_BP_UnstablePowerCores_GrenadeScript
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UnstablePowerCores_GrenadeScript_C::ExecuteUbergraph_BP_UnstablePowerCores_GrenadeScript(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UnstablePowerCores_GrenadeScript_C", "ExecuteUbergraph_BP_UnstablePowerCores_GrenadeScript");

	Params::BP_UnstablePowerCores_GrenadeScript_C_ExecuteUbergraph_BP_UnstablePowerCores_GrenadeScript Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UnstablePowerCores_GrenadeScript.BP_UnstablePowerCores_GrenadeScript_C.K2_ApplyStatusEffects
// (Event, Public, BlueprintEvent)

void UBP_UnstablePowerCores_GrenadeScript_C::K2_ApplyStatusEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UnstablePowerCores_GrenadeScript_C", "K2_ApplyStatusEffects");

	UObject::ProcessEvent(Func, nullptr);
}

}

