#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UnlockAllEngineRifleMods_Challenge

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UnlockAllEngineRifleMods_Challenge.BP_UnlockAllEngineRifleMods_Challenge_C
// 0x0018 (0x0048 - 0x0030)
class UBP_UnlockAllEngineRifleMods_Challenge_C final : public URChallengeScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class FName>                           ChallengesRequired;                                // 0x0038(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void CheckCompletedChallenges(int32* CompletedChallenges);
	void ExecuteUbergraph_BP_UnlockAllEngineRifleMods_Challenge(int32 EntryPoint);
	void OnApplicableRunStarted();
	void OnChallengeCompleted(const struct FRChallenge& Challenge);
	void OnRunFinished(bool RunFailed);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UnlockAllEngineRifleMods_Challenge_C">();
	}
	static class UBP_UnlockAllEngineRifleMods_Challenge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UnlockAllEngineRifleMods_Challenge_C>();
	}
};
static_assert(alignof(UBP_UnlockAllEngineRifleMods_Challenge_C) == 0x000008, "Wrong alignment on UBP_UnlockAllEngineRifleMods_Challenge_C");
static_assert(sizeof(UBP_UnlockAllEngineRifleMods_Challenge_C) == 0x000048, "Wrong size on UBP_UnlockAllEngineRifleMods_Challenge_C");
static_assert(offsetof(UBP_UnlockAllEngineRifleMods_Challenge_C, UberGraphFrame) == 0x000030, "Member 'UBP_UnlockAllEngineRifleMods_Challenge_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_UnlockAllEngineRifleMods_Challenge_C, ChallengesRequired) == 0x000038, "Member 'UBP_UnlockAllEngineRifleMods_Challenge_C::ChallengesRequired' has a wrong offset!");

}

