#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_SubtitleContainer

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Widget_SubtitleContainer.Widget_SubtitleContainer_C.ExecuteUbergraph_Widget_SubtitleContainer
// 0x0100 (0x0100 - 0x0000)
struct Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class APlayerState* PlayerState)> K2Node_CreateDelegate_OutputDelegate;           // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_27[0x1];                                       // 0x0027(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UAudioComponent* PlayingVoiceAC, class FText PlayerName, class FText Subtitle)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        K2Node_CustomEvent_PlayingVoiceAC;                 // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_PlayerName;                     // 0x0050(0x0010)()
	class FText                                   K2Node_CustomEvent_Subtitle;                       // 0x0060(0x0010)()
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget_SubtitleEntry_C*                CallFunc_Create_ReturnValue;                       // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0090(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_AreAnyListenersWithinRange_ReturnValue;   // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARGameState*                            CallFunc_GetRGameState_ReturnValue;                // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerState*                           K2Node_CustomEvent_PlayerState;                    // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class ARPlayerPawn*>                   CallFunc_GetAllPlayerPawnsInLevel_ReturnValue;     // 0x00D0(0x0010)(ReferenceParm)
	class ARPlayerPawn*                           CallFunc_Array_Get_Item;                           // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_ED[0x3];                                       // 0x00ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue;         // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue;                       // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer) == 0x000008, "Wrong alignment on Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer");
static_assert(sizeof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer) == 0x000100, "Wrong size on Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, EntryPoint) == 0x000000, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::EntryPoint' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, Temp_bool_Variable) == 0x000024, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, Temp_byte_Variable) == 0x000025, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, Temp_byte_Variable_1) == 0x000026, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, Temp_int_Array_Index_Variable) == 0x000028, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, Temp_int_Loop_Counter_Variable) == 0x00002C, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_Add_IntInt_ReturnValue) == 0x000030, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CreateDelegate_OutputDelegate_2) == 0x000034, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CustomEvent_PlayingVoiceAC) == 0x000048, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CustomEvent_PlayingVoiceAC' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CustomEvent_PlayerName) == 0x000050, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CustomEvent_PlayerName' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CustomEvent_Subtitle) == 0x000060, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CustomEvent_Subtitle' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_GetOwningPlayer_ReturnValue) == 0x000070, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_TextIsEmpty_ReturnValue) == 0x000078, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_Create_ReturnValue) == 0x000080, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_Not_PreBool_ReturnValue) == 0x000088, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000090, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_AreAnyListenersWithinRange_ReturnValue) == 0x0000A8, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_AreAnyListenersWithinRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_AddChild_ReturnValue) == 0x0000B0, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_BooleanAND_ReturnValue) == 0x0000B8, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_GetRGameState_ReturnValue) == 0x0000C0, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_GetRGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CustomEvent_PlayerState) == 0x0000C8, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CustomEvent_PlayerState' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_GetAllPlayerPawnsInLevel_ReturnValue) == 0x0000D0, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_GetAllPlayerPawnsInLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_Array_Get_Item) == 0x0000E0, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_Array_Length_ReturnValue) == 0x0000E8, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_Less_IntInt_ReturnValue) == 0x0000EC, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, CallFunc_GetRGameUserSettings_ReturnValue) == 0x0000F0, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::CallFunc_GetRGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_CustomEvent_NewValue) == 0x0000F8, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_CustomEvent_NewValue' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer, K2Node_Select_Default) == 0x0000F9, "Member 'Widget_SubtitleContainer_C_ExecuteUbergraph_Widget_SubtitleContainer::K2Node_Select_Default' has a wrong offset!");

// Function Widget_SubtitleContainer.Widget_SubtitleContainer_C.OnPlayerJoined_Event
// 0x0008 (0x0008 - 0x0000)
struct Widget_SubtitleContainer_C_OnPlayerJoined_Event final
{
public:
	class APlayerState*                           PlayerState;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_SubtitleContainer_C_OnPlayerJoined_Event) == 0x000008, "Wrong alignment on Widget_SubtitleContainer_C_OnPlayerJoined_Event");
static_assert(sizeof(Widget_SubtitleContainer_C_OnPlayerJoined_Event) == 0x000008, "Wrong size on Widget_SubtitleContainer_C_OnPlayerJoined_Event");
static_assert(offsetof(Widget_SubtitleContainer_C_OnPlayerJoined_Event, PlayerState) == 0x000000, "Member 'Widget_SubtitleContainer_C_OnPlayerJoined_Event::PlayerState' has a wrong offset!");

// Function Widget_SubtitleContainer.Widget_SubtitleContainer_C.OnShowSubtitlesUpdated_Event
// 0x0001 (0x0001 - 0x0000)
struct Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event) == 0x000001, "Wrong alignment on Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event");
static_assert(sizeof(Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event) == 0x000001, "Wrong size on Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event");
static_assert(offsetof(Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event, NewValue) == 0x000000, "Member 'Widget_SubtitleContainer_C_OnShowSubtitlesUpdated_Event::NewValue' has a wrong offset!");

// Function Widget_SubtitleContainer.Widget_SubtitleContainer_C.OnVoiceLinePlayed
// 0x0028 (0x0028 - 0x0000)
struct Widget_SubtitleContainer_C_OnVoiceLinePlayed final
{
public:
	class UAudioComponent*                        PlayingVoiceAC;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   PlayerName;                                        // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Subtitle;                                          // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Widget_SubtitleContainer_C_OnVoiceLinePlayed) == 0x000008, "Wrong alignment on Widget_SubtitleContainer_C_OnVoiceLinePlayed");
static_assert(sizeof(Widget_SubtitleContainer_C_OnVoiceLinePlayed) == 0x000028, "Wrong size on Widget_SubtitleContainer_C_OnVoiceLinePlayed");
static_assert(offsetof(Widget_SubtitleContainer_C_OnVoiceLinePlayed, PlayingVoiceAC) == 0x000000, "Member 'Widget_SubtitleContainer_C_OnVoiceLinePlayed::PlayingVoiceAC' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_OnVoiceLinePlayed, PlayerName) == 0x000008, "Member 'Widget_SubtitleContainer_C_OnVoiceLinePlayed::PlayerName' has a wrong offset!");
static_assert(offsetof(Widget_SubtitleContainer_C_OnVoiceLinePlayed, Subtitle) == 0x000018, "Member 'Widget_SubtitleContainer_C_OnVoiceLinePlayed::Subtitle' has a wrong offset!");

}

