#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_DemoEndScreen

#include "Basic.hpp"

#include "CommonInput_structs.hpp"


namespace SDK::Params
{

// Function Widget_DemoEndScreen.Widget_DemoEndScreen_C.ExecuteUbergraph_Widget_DemoEndScreen
// 0x0040 (0x0040 - 0x0000)
struct Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_2;               // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen) == 0x000008, "Wrong alignment on Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen");
static_assert(sizeof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen) == 0x000040, "Wrong size on Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, EntryPoint) == 0x000000, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, CallFunc_GetCurrentInputType_ReturnValue) == 0x000011, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000012, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, K2Node_ComponentBoundEvent_Button_2) == 0x000018, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::K2Node_ComponentBoundEvent_Button_2' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, K2Node_ComponentBoundEvent_Button_1) == 0x000020, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, K2Node_ComponentBoundEvent_Button) == 0x000028, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, CallFunc_GetOwningPlayer_ReturnValue) == 0x000030, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen, CallFunc_PlayAnimation_ReturnValue) == 0x000038, "Member 'Widget_DemoEndScreen_C_ExecuteUbergraph_Widget_DemoEndScreen::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function Widget_DemoEndScreen.Widget_DemoEndScreen_C.BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function Widget_DemoEndScreen.Widget_DemoEndScreen_C.BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function Widget_DemoEndScreen.Widget_DemoEndScreen_C.BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_DemoEndScreen_C_BndEvt__Widget_DemoEndScreen_SteamButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

}

