#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_CosmeticEntryContentMesh

#include "Basic.hpp"

#include "Widget_CosmeticEntryContentMesh_classes.hpp"
#include "Widget_CosmeticEntryContentMesh_parameters.hpp"


namespace SDK
{

// Function Widget_CosmeticEntryContentMesh.Widget_CosmeticEntryContentMesh_C.SetContentInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPlayerCosmeticOption&     CosmeticOptionData                                     (BlueprintVisible, BlueprintReadOnly, Parm)

void UWidget_CosmeticEntryContentMesh_C::SetContentInfo(const struct FPlayerCosmeticOption& CosmeticOptionData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CosmeticEntryContentMesh_C", "SetContentInfo");

	Params::Widget_CosmeticEntryContentMesh_C_SetContentInfo Parms{};

	Parms.CosmeticOptionData = std::move(CosmeticOptionData);

	UObject::ProcessEvent(Func, &Parms);
}

}

