#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_OffScreenIndication_PlayerDowned

#include "Basic.hpp"

#include "Widget_OffScreenIndication_PlayerDowned_classes.hpp"
#include "Widget_OffScreenIndication_PlayerDowned_parameters.hpp"


namespace SDK
{

// Function Widget_OffScreenIndication_PlayerDowned.Widget_OffScreenIndication_PlayerDowned_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_OffScreenIndication_PlayerDowned_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_OffScreenIndication_PlayerDowned_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_OffScreenIndication_PlayerDowned.Widget_OffScreenIndication_PlayerDowned_C.ExecuteUbergraph_Widget_OffScreenIndication_PlayerDowned
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_OffScreenIndication_PlayerDowned_C::ExecuteUbergraph_Widget_OffScreenIndication_PlayerDowned(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_OffScreenIndication_PlayerDowned_C", "ExecuteUbergraph_Widget_OffScreenIndication_PlayerDowned");

	Params::Widget_OffScreenIndication_PlayerDowned_C_ExecuteUbergraph_Widget_OffScreenIndication_PlayerDowned Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_OffScreenIndication_PlayerDowned.Widget_OffScreenIndication_PlayerDowned_C.UpdateTarget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           TargetActor_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  DangerousRadius                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  CloseRadius                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CriticalDanger                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   DangerousLocation                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_OffScreenIndication_PlayerDowned_C::UpdateTarget(class AActor* TargetActor_0, double DangerousRadius, double CloseRadius, bool CriticalDanger, const struct FVector& DangerousLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_OffScreenIndication_PlayerDowned_C", "UpdateTarget");

	Params::Widget_OffScreenIndication_PlayerDowned_C_UpdateTarget Parms{};

	Parms.TargetActor_0 = TargetActor_0;
	Parms.DangerousRadius = DangerousRadius;
	Parms.CloseRadius = CloseRadius;
	Parms.CriticalDanger = CriticalDanger;
	Parms.DangerousLocation = std::move(DangerousLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_OffScreenIndication_PlayerDowned.Widget_OffScreenIndication_PlayerDowned_C.UpdateTransform
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_OffScreenIndication_PlayerDowned_C::UpdateTransform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_OffScreenIndication_PlayerDowned_C", "UpdateTransform");

	UObject::ProcessEvent(Func, nullptr);
}

}

