#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_CommonInviteMenu

#include "Basic.hpp"

#include "Widget_CommonInviteMenu_classes.hpp"
#include "Widget_CommonInviteMenu_parameters.hpp"


namespace SDK
{

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget_TextButton_C*             Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature(class UWidget_TextButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature");

	Params::Widget_CommonInviteMenu_C_BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget_TextButton_C*             Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature(class UWidget_TextButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature");

	Params::Widget_CommonInviteMenu_C_BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget_TextButton_C*             Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature(class UWidget_TextButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature");

	Params::Widget_CommonInviteMenu_C_BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget_TextButton_C*             Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature(class UWidget_TextButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature");

	Params::Widget_CommonInviteMenu_C_BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BP_OnHandleBackAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWidget_CommonInviteMenu_C::BP_OnHandleBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "BP_OnHandleBackAction");

	Params::Widget_CommonInviteMenu_C_BP_OnHandleBackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_CommonInviteMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.ExecuteUbergraph_Widget_CommonInviteMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::ExecuteUbergraph_Widget_CommonInviteMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "ExecuteUbergraph_Widget_CommonInviteMenu");

	Params::Widget_CommonInviteMenu_C_ExecuteUbergraph_Widget_CommonInviteMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.GetFocusedMenuButton
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget_TextButton_C**            Button                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::GetFocusedMenuButton(class UWidget_TextButton_C** Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "GetFocusedMenuButton");

	Params::Widget_CommonInviteMenu_C_GetFocusedMenuButton Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Button != nullptr)
		*Button = Parms.Button;
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.OnVisibilityChanged_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_CommonInviteMenu_C::OnVisibilityChanged_Event(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "OnVisibilityChanged_Event");

	Params::Widget_CommonInviteMenu_C_OnVisibilityChanged_Event Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SessionBrowserPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CommonInviteMenu_C::SessionBrowserPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "SessionBrowserPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SessionSettingsPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CommonInviteMenu_C::SessionSettingsPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "SessionSettingsPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SetSessionBrowserButtonVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CommonInviteMenu_C::SetSessionBrowserButtonVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "SetSessionBrowserButtonVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SetSessionSettingsButtonVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CommonInviteMenu_C::SetSessionSettingsButtonVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "SetSessionSettingsButtonVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SetWidgetFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CommonInviteMenu_C::SetWidgetFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "SetWidgetFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWidget_CommonInviteMenu_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CommonInviteMenu_C", "BP_GetDesiredFocusTarget");

	Params::Widget_CommonInviteMenu_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

