#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_ChallengesCompletedPopup

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.SetUnlockVisuals
// 0x0038 (0x0038 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_SetUnlockVisuals final
{
public:
	class UTexture2D*                             Icon;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Name_0;                                            // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Description;                                       // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   TopTitle;                                          // 0x0028(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_SetUnlockVisuals) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_SetUnlockVisuals");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_SetUnlockVisuals) == 0x000038, "Wrong size on Widget_ChallengesCompletedPopup_C_SetUnlockVisuals");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_SetUnlockVisuals, Icon) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_SetUnlockVisuals::Icon' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_SetUnlockVisuals, Name_0) == 0x000008, "Member 'Widget_ChallengesCompletedPopup_C_SetUnlockVisuals::Name_0' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_SetUnlockVisuals, Description) == 0x000018, "Member 'Widget_ChallengesCompletedPopup_C_SetUnlockVisuals::Description' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_SetUnlockVisuals, TopTitle) == 0x000028, "Member 'Widget_ChallengesCompletedPopup_C_SetUnlockVisuals::TopTitle' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.Set Continue Text
// 0x00A8 (0x00A8 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_Set_Continue_Text final
{
public:
	int32                                         ChallengeIndex_0;                                  // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0010)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0030(0x0048)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0010)()
	class FText                                   K2Node_Select_Default;                             // 0x0098(0x0010)()
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_Set_Continue_Text");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text) == 0x0000A8, "Wrong size on Widget_ChallengesCompletedPopup_C_Set_Continue_Text");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, ChallengeIndex_0) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::ChallengeIndex_0' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, Temp_bool_Variable) == 0x000004, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, Temp_text_Variable) == 0x000008, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, CallFunc_Subtract_IntInt_ReturnValue) == 0x00001C, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, CallFunc_Conv_IntToInt64_ReturnValue) == 0x000020, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, CallFunc_Greater_IntInt_ReturnValue) == 0x000028, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, K2Node_MakeStruct_FormatArgumentData) == 0x000030, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, K2Node_MakeArray_Array) == 0x000078, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, CallFunc_Format_ReturnValue) == 0x000088, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Set_Continue_Text, K2Node_Select_Default) == 0x000098, "Member 'Widget_ChallengesCompletedPopup_C_Set_Continue_Text::K2Node_Select_Default' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.Initialize
// 0x0018 (0x0018 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_Initialize final
{
public:
	TArray<class URChallengeGridItem*>            GridItems;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          CallFunc_Array_IsNotEmpty_ReturnValue;             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_Initialize) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_Initialize");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_Initialize) == 0x000018, "Wrong size on Widget_ChallengesCompletedPopup_C_Initialize");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Initialize, GridItems) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_Initialize::GridItems' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_Initialize, CallFunc_Array_IsNotEmpty_ReturnValue) == 0x000010, "Member 'Widget_ChallengesCompletedPopup_C_Initialize::CallFunc_Array_IsNotEmpty_ReturnValue' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.GetRewardTypeName
// 0x0078 (0x0078 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_GetRewardTypeName final
{
public:
	class URPrimaryDataAsset*                     RewardDA;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Name_0;                                            // 0x0008(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URWeaponPrimaryAsset*                   K2Node_DynamicCast_AsRWeapon_Primary_Asset;        // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URWeaponModPrimaryAsset*                K2Node_DynamicCast_AsRWeapon_Mod_Primary_Asset;    // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URMutatorPrimaryAsset*                  K2Node_DynamicCast_AsRMutator_Primary_Asset;       // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x0050(0x0020)()
	bool                                          CallFunc_HasTag_ReturnValue;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_GetRewardTypeName");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName) == 0x000078, "Wrong size on Widget_ChallengesCompletedPopup_C_GetRewardTypeName");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, RewardDA) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::RewardDA' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, Name_0) == 0x000008, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::Name_0' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, K2Node_DynamicCast_AsRWeapon_Primary_Asset) == 0x000020, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::K2Node_DynamicCast_AsRWeapon_Primary_Asset' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, K2Node_DynamicCast_AsRWeapon_Mod_Primary_Asset) == 0x000030, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::K2Node_DynamicCast_AsRWeapon_Mod_Primary_Asset' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, K2Node_DynamicCast_AsRMutator_Primary_Asset) == 0x000040, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::K2Node_DynamicCast_AsRMutator_Primary_Asset' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, K2Node_DynamicCast_bSuccess_2) == 0x000048, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x000050, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GetRewardTypeName, CallFunc_HasTag_ReturnValue) == 0x000070, "Member 'Widget_ChallengesCompletedPopup_C_GetRewardTypeName::CallFunc_HasTag_ReturnValue' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.GenerateUnlockWidget
// 0x0004 (0x0004 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget) == 0x000004, "Wrong alignment on Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget) == 0x000004, "Wrong size on Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget, Index_0) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_GenerateUnlockWidget::Index_0' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.ExecuteUbergraph_Widget_ChallengesCompletedPopup
// 0x01C0 (0x01C0 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_index;                          // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ARChallengeManager*                     CallFunc_GetChallengeManager_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URChallengeGridItem*                    CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_ParseChallengeDescription_ReturnValue;    // 0x0040(0x0010)()
	class URPrimaryDataAsset*                     CallFunc_GetChallengeRewardAssets_OutReward;       // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChallengeRewardAssets_OutSoulFragmentsReward; // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetChallengeRewardAssets_ReturnValue;     // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5E[0x2];                                       // 0x005E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0068(0x0048)(HasGetValueTypeHash)
	class URWeaponPrimaryAsset*                   K2Node_DynamicCast_AsRWeapon_Primary_Asset;        // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00C0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00D0(0x0010)()
	class URWeaponModPrimaryAsset*                K2Node_DynamicCast_AsRWeapon_Mod_Primary_Asset;    // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URCharacterMutatorPrimaryAsset*         K2Node_DynamicCast_AsRCharacter_Mutator_Primary_Asset; // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_ParseMutatorDescription_ReturnValue;      // 0x0100(0x0010)()
	class FText                                   CallFunc_GetRewardTypeName_Name;                   // 0x0110(0x0010)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0120(0x0048)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0168(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0180(0x0010)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x019C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19D[0x3];                                      // 0x019D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x01A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x01B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B3[0x5];                                      // 0x01B3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup) == 0x0001C0, "Wrong size on Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, EntryPoint) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::EntryPoint' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, Temp_int_Variable) == 0x000004, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_GetOwningPlayer_ReturnValue) == 0x000010, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_CustomEvent_index) == 0x000018, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_CustomEvent_index' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_GetChallengeManager_ReturnValue) == 0x000020, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_GetChallengeManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, Temp_bool_Variable) == 0x000028, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Array_Get_Item) == 0x000030, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000038, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_ParseChallengeDescription_ReturnValue) == 0x000040, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_ParseChallengeDescription_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_GetChallengeRewardAssets_OutReward) == 0x000050, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_GetChallengeRewardAssets_OutReward' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_GetChallengeRewardAssets_OutSoulFragmentsReward) == 0x000058, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_GetChallengeRewardAssets_OutSoulFragmentsReward' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_GetChallengeRewardAssets_ReturnValue) == 0x00005C, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_GetChallengeRewardAssets_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Greater_IntInt_ReturnValue) == 0x00005D, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Conv_IntToInt64_ReturnValue) == 0x000060, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_MakeStruct_FormatArgumentData) == 0x000068, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_DynamicCast_AsRWeapon_Primary_Asset) == 0x0000B0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_DynamicCast_AsRWeapon_Primary_Asset' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_DynamicCast_bSuccess) == 0x0000B8, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_MakeArray_Array) == 0x0000C0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Format_ReturnValue) == 0x0000D0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_DynamicCast_AsRWeapon_Mod_Primary_Asset) == 0x0000E0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_DynamicCast_AsRWeapon_Mod_Primary_Asset' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_DynamicCast_bSuccess_1) == 0x0000E8, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_DynamicCast_AsRCharacter_Mutator_Primary_Asset) == 0x0000F0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_DynamicCast_AsRCharacter_Mutator_Primary_Asset' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_DynamicCast_bSuccess_2) == 0x0000F8, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_ParseMutatorDescription_ReturnValue) == 0x000100, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_ParseMutatorDescription_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_GetRewardTypeName_Name) == 0x000110, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_GetRewardTypeName_Name' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_MakeStruct_FormatArgumentData_1) == 0x000120, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_MakeArray_Array_1) == 0x000168, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_IsValid_ReturnValue) == 0x000178, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Format_ReturnValue_1) == 0x000180, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Array_Length_ReturnValue) == 0x000190, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Subtract_IntInt_ReturnValue) == 0x000194, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Add_IntInt_ReturnValue) == 0x000198, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_Greater_IntInt_ReturnValue_1) == 0x00019C, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_ComponentBoundEvent_Button_1) == 0x0001A0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_ComponentBoundEvent_Button) == 0x0001A8, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, Temp_byte_Variable) == 0x0001B0, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, Temp_byte_Variable_1) == 0x0001B1, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, K2Node_Select_Default) == 0x0001B2, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup, CallFunc_PlayAnimation_ReturnValue_1) == 0x0001B8, "Member 'Widget_ChallengesCompletedPopup_C_ExecuteUbergraph_Widget_ChallengesCompletedPopup::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Skip_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function Widget_ChallengesCompletedPopup.Widget_ChallengesCompletedPopup_C.BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_ChallengesCompletedPopup_C_BndEvt__Widget_ChallengesCompletedPopup_W_Button_Continue_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

}

