#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_ArtifactUpgradeSelectScreen

#include "Basic.hpp"

#include "Widget_ArtifactUpgradeSelectScreen_classes.hpp"
#include "Widget_ArtifactUpgradeSelectScreen_parameters.hpp"


namespace SDK
{

// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.BndEvt__Widget_AbilitySelectScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWidget_ArtifactUpgradeSelectScreen_C::BndEvt__Widget_AbilitySelectScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "BndEvt__Widget_AbilitySelectScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::Widget_ArtifactUpgradeSelectScreen_C_BndEvt__Widget_AbilitySelectScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_ArtifactUpgradeSelectScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.ExecuteUbergraph_Widget_ArtifactUpgradeSelectScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_ArtifactUpgradeSelectScreen_C::ExecuteUbergraph_Widget_ArtifactUpgradeSelectScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "ExecuteUbergraph_Widget_ArtifactUpgradeSelectScreen");

	Params::Widget_ArtifactUpgradeSelectScreen_C_ExecuteUbergraph_Widget_ArtifactUpgradeSelectScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.Finished_44A434EB46D3B5E477B7DA94A49A00D3
// (BlueprintCallable, BlueprintEvent)

void UWidget_ArtifactUpgradeSelectScreen_C::Finished_44A434EB46D3B5E477B7DA94A49A00D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "Finished_44A434EB46D3B5E477B7DA94A49A00D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.Initialize
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FRLootSelectionOption>&   LootOptions_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FGameplayTag&              LootSelectionType_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class ARPickupableItem*                 PickupableItem                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EOrientation                            OptionOrientation                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_ArtifactUpgradeSelectScreen_C::Initialize(TArray<struct FRLootSelectionOption>& LootOptions_0, const struct FGameplayTag& LootSelectionType_0, class ARPickupableItem* PickupableItem, EOrientation OptionOrientation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "Initialize");

	Params::Widget_ArtifactUpgradeSelectScreen_C_Initialize Parms{};

	Parms.LootOptions_0 = std::move(LootOptions_0);
	Parms.LootSelectionType_0 = std::move(LootSelectionType_0);
	Parms.PickupableItem = PickupableItem;
	Parms.OptionOrientation = OptionOrientation;

	UObject::ProcessEvent(Func, &Parms);

	LootOptions_0 = std::move(Parms.LootOptions_0);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.OnLooted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRLootSelectionOption&     LootSelectionOption                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWidget_ArtifactUpgradeSelectScreen_C::OnLooted(const struct FRLootSelectionOption& LootSelectionOption)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "OnLooted");

	Params::Widget_ArtifactUpgradeSelectScreen_C_OnLooted Parms{};

	Parms.LootSelectionOption = std::move(LootSelectionOption);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.ShowLootOptions
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWidget_ArtifactUpgradeSelectScreen_C::ShowLootOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "ShowLootOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWidget_ArtifactUpgradeSelectScreen_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_ArtifactUpgradeSelectScreen_C", "BP_GetDesiredFocusTarget");

	Params::Widget_ArtifactUpgradeSelectScreen_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

