#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_CommonSessionBrowser

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "DMOnlinePlugin_structs.hpp"
#include "Engine_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"


namespace SDK::Params
{

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.Success_89DC13C346A98A5EE7ADA9A586F0AEA2
// 0x0020 (0x0020 - 0x0000)
struct Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2 final
{
public:
	class FString                                 Error;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FBlueprintSessionResult>        Result;                                            // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2");
static_assert(sizeof(Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2) == 0x000020, "Wrong size on Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2");
static_assert(offsetof(Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2, Error) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2::Error' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2, Result) == 0x000010, "Member 'Widget_CommonSessionBrowser_C_Success_89DC13C346A98A5EE7ADA9A586F0AEA2::Result' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.SetRefreshButtonsEnabled
// 0x0001 (0x0001 - 0x0000)
struct Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled) == 0x000001, "Wrong alignment on Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled");
static_assert(sizeof(Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled) == 0x000001, "Wrong size on Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled");
static_assert(offsetof(Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled, Enabled) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_SetRefreshButtonsEnabled::Enabled' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.NavigateToFirstSession
// 0x0050 (0x0050 - 0x0000)
struct Widget_CommonSessionBrowser_C_NavigateToFirstSession final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsEnabled_ReturnValue;                 // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUserWidget*>                    CallFunc_GetDisplayedEntryWidgets_ReturnValue;     // 0x0018(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget_CommonSessionEntry_C*           K2Node_DynamicCast_AsWidget_Common_Session_Entry;  // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_NavigateToFirstSession) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_NavigateToFirstSession");
static_assert(sizeof(Widget_CommonSessionBrowser_C_NavigateToFirstSession) == 0x000050, "Wrong size on Widget_CommonSessionBrowser_C_NavigateToFirstSession");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, Navigation_0) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::Navigation_0' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, ReturnValue) == 0x000008, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, CallFunc_GetIsEnabled_ReturnValue) == 0x000010, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::CallFunc_GetIsEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, CallFunc_GetDisplayedEntryWidgets_ReturnValue) == 0x000018, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::CallFunc_GetDisplayedEntryWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000028, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, CallFunc_Array_Get_Item) == 0x000030, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, CallFunc_IsValid_ReturnValue) == 0x000038, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, K2Node_DynamicCast_AsWidget_Common_Session_Entry) == 0x000040, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::K2Node_DynamicCast_AsWidget_Common_Session_Entry' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_NavigateToFirstSession, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'Widget_CommonSessionBrowser_C_NavigateToFirstSession::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.Fail_89DC13C346A98A5EE7ADA9A586F0AEA2
// 0x0020 (0x0020 - 0x0000)
struct Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2 final
{
public:
	class FString                                 Error;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FBlueprintSessionResult>        Result;                                            // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2");
static_assert(sizeof(Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2) == 0x000020, "Wrong size on Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2");
static_assert(offsetof(Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2, Error) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2::Error' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2, Result) == 0x000010, "Member 'Widget_CommonSessionBrowser_C_Fail_89DC13C346A98A5EE7ADA9A586F0AEA2::Result' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.ExecuteUbergraph_Widget_CommonSessionBrowser
// 0x0450 (0x0450 - 0x0000)
struct Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_ComponentBoundEvent_Item;                   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            K2Node_ComponentBoundEvent_Widget;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_CommonSessionEntry_C*           K2Node_DynamicCast_AsWidget_Common_Session_Entry;  // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSessionInfoContainer*                 K2Node_DynamicCast_AsRSession_Info_Container;      // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& Error, const TArray<struct FBlueprintSessionResult>& Result)> K2Node_CreateDelegate_OutputDelegate; // 0x003C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class URSessionInfoContainer*                 CallFunc_SpawnObject_ReturnValue;                  // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x005C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetUnpausedTimeSeconds_ReturnValue;       // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetUnpausedTimeSeconds_ReturnValue_1;     // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0098(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, struct FDMSearchSetting>    CallFunc_BuildFilter_OutFilterMap;                 // 0x00A8(0x0050)()
	class USPFindSessionBlueprintProxy*           CallFunc_CreateFindSessionProxyObject_ReturnValue; // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_Text_1;                 // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumItems_ReturnValue;                  // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_StringToInt_ReturnValue;             // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0128(0x0010)()
	class FString                                 K2Node_ComponentBoundEvent_Text;                   // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_StringToInt_ReturnValue_1;           // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0150(0x0010)()
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0168(0x0010)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0180(0x0010)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_StringToInt_ReturnValue_2;           // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x01A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A5[0x3];                                      // 0x01A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x01A8(0x0010)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue_1;                // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_1;                           // 0x01C0(0x0010)()
	class FString                                 Temp_string_Variable;                              // 0x01D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x01E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x01F0(0x0010)()
	int32                                         CallFunc_Conv_StringToInt_ReturnValue_3;           // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_204[0x4];                                      // 0x0204(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0208(0x0048)(HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0258(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0268(0x0010)()
	TArray<struct FBlueprintSessionResult>        Temp_struct_Variable;                              // 0x0278(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x0291(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_292[0x6];                                      // 0x0292(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_Error;                          // 0x0298(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Result;                         // 0x02A8(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const class FString& Error, const TArray<struct FBlueprintSessionResult>& Result)> K2Node_CreateDelegate_OutputDelegate_2; // 0x02B8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Enabled;                        // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C9[0x3];                                      // 0x02C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x02CC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DC[0x4];                                      // 0x02DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_2;               // 0x02E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x02E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Error_1;                        // 0x02F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Result_1;                       // 0x0300(0x0010)(ConstParm, ReferenceParm)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0318(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FBlueprintSessionResult                CallFunc_Array_Get_Item;                           // 0x0320(0x0120)()
	int32                                         CallFunc_GetCurrentPlayers_ReturnValue;            // 0x0440(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_3;             // 0x0444(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_445[0x3];                                      // 0x0445(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_K2_SetTimerDelegate_Time_ImplicitCast;    // 0x0448(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser");
static_assert(sizeof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser) == 0x000450, "Wrong size on Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, EntryPoint) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::EntryPoint' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Item) == 0x000010, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Item' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Widget) == 0x000018, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Widget' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_DynamicCast_AsWidget_Common_Session_Entry) == 0x000020, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_DynamicCast_AsWidget_Common_Session_Entry' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_DynamicCast_AsRSession_Info_Container) == 0x000030, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_DynamicCast_AsRSession_Info_Container' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CreateDelegate_OutputDelegate) == 0x00003C, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_bool_Variable) == 0x00004C, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_SpawnObject_ReturnValue) == 0x000050, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_bool_Variable_1) == 0x000058, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CreateDelegate_OutputDelegate_1) == 0x00005C, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GetUnpausedTimeSeconds_ReturnValue) == 0x000070, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GetUnpausedTimeSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GetUnpausedTimeSeconds_ReturnValue_1) == 0x000078, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GetUnpausedTimeSeconds_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000080, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x000088, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000090, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000098, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_bool_Has_Been_Initd_Variable) == 0x0000A0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_BuildFilter_OutFilterMap) == 0x0000A8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_BuildFilter_OutFilterMap' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_CreateFindSessionProxyObject_ReturnValue) == 0x0000F8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_CreateFindSessionProxyObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_IsValid_ReturnValue) == 0x000100, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Text_1) == 0x000108, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Text_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GetNumItems_ReturnValue) == 0x000118, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GetNumItems_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_StringToInt_ReturnValue) == 0x00011C, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_StringToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Greater_IntInt_ReturnValue) == 0x000120, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_IntToText_ReturnValue) == 0x000128, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Text) == 0x000138, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_StringToInt_ReturnValue_1) == 0x000148, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_StringToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000150, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_bool_IsClosed_Variable) == 0x000160, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GetText_ReturnValue) == 0x000168, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_TextIsEmpty_ReturnValue) == 0x000178, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_Select_Default) == 0x000180, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_TextToString_ReturnValue) == 0x000190, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_StringToInt_ReturnValue_2) == 0x0001A0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_StringToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Greater_IntInt_ReturnValue_1) == 0x0001A4, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GetText_ReturnValue_1) == 0x0001A8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GetText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_TextIsEmpty_ReturnValue_1) == 0x0001B8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_TextIsEmpty_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_Select_Default_1) == 0x0001C0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_string_Variable) == 0x0001D0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_TextToString_ReturnValue_1) == 0x0001E0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_StringToText_ReturnValue) == 0x0001F0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Conv_StringToInt_ReturnValue_3) == 0x000200, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Conv_StringToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_MakeStruct_FormatArgumentData) == 0x000208, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Less_IntInt_ReturnValue) == 0x000250, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_MakeArray_Array) == 0x000258, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Format_ReturnValue) == 0x000268, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_struct_Variable) == 0x000278, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Array_Length_ReturnValue) == 0x000288, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Array_Length_ReturnValue_1) == 0x00028C, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Less_IntInt_ReturnValue_1) == 0x000290, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Greater_IntInt_ReturnValue_2) == 0x000291, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CustomEvent_Error) == 0x000298, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CustomEvent_Error' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CustomEvent_Result) == 0x0002A8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CustomEvent_Result' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CreateDelegate_OutputDelegate_2) == 0x0002B8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CustomEvent_Enabled) == 0x0002C8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CustomEvent_Enabled' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CreateDelegate_OutputDelegate_3) == 0x0002CC, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Button_2) == 0x0002E0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Button_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Button_1) == 0x0002E8, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CustomEvent_Error_1) == 0x0002F0, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CustomEvent_Error_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_CustomEvent_Result_1) == 0x000300, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_CustomEvent_Result_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, Temp_int_Array_Index_Variable) == 0x000310, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, K2Node_ComponentBoundEvent_Button) == 0x000318, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Array_Get_Item) == 0x000320, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_GetCurrentPlayers_ReturnValue) == 0x000440, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_GetCurrentPlayers_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_Greater_IntInt_ReturnValue_3) == 0x000444, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_Greater_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser, CallFunc_K2_SetTimerDelegate_Time_ImplicitCast) == 0x000448, "Member 'Widget_CommonSessionBrowser_C_ExecuteUbergraph_Widget_CommonSessionBrowser::CallFunc_K2_SetTimerDelegate_Time_ImplicitCast' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BuildFilter
// 0x01E8 (0x01E8 - 0x0000)
struct Widget_CommonSessionBrowser_C_BuildFilter final
{
public:
	TMap<class FName, struct FDMSearchSetting>    OutFilterMap;                                      // 0x0000(0x0050)(Parm, OutParm)
	TMap<class FName, struct FDMSearchSetting>    FilterMap;                                         // 0x0050(0x0050)(Edit, BlueprintVisible)
	struct FDMSearchSetting                       K2Node_MakeStruct_DMSearchSetting;                 // 0x00A0(0x0018)()
	class FName                                   CallFunc_GetFilter_Key;                            // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetFilter_Value;                          // 0x00C0(0x0010)()
	class FName                                   Temp_name_Variable;                                // 0x00D0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDMSearchSetting                       K2Node_MakeStruct_DMSearchSetting_1;               // 0x00E8(0x0018)()
	class FName                                   CallFunc_GetFilter_Key_1;                          // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetFilter_Value_1;                        // 0x0108(0x0010)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDMSearchSetting                       K2Node_MakeStruct_DMSearchSetting_2;               // 0x0128(0x0018)()
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDMSearchSetting                       K2Node_MakeStruct_DMSearchSetting_3;               // 0x0148(0x0018)()
	class FString                                 CallFunc_Conv_ByteToString_ReturnValue;            // 0x0160(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDMSearchSetting                       K2Node_MakeStruct_DMSearchSetting_4;               // 0x0170(0x0018)()
	class FName                                   Temp_name_Variable_1;                              // 0x0188(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetValue_ReturnValue;                     // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_GetFilter_Key_2;                          // 0x0194(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetFilter_Value_2;                        // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDMSearchSetting                       K2Node_MakeStruct_DMSearchSetting_5;               // 0x01B0(0x0018)()
	bool                                          CallFunc_GetValue_ReturnValue_1;                   // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C9[0x3];                                      // 0x01C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_GetFilter_Key_3;                          // 0x01CC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D4[0x4];                                      // 0x01D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetFilter_Value_3;                        // 0x01D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BuildFilter) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BuildFilter");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BuildFilter) == 0x0001E8, "Wrong size on Widget_CommonSessionBrowser_C_BuildFilter");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, OutFilterMap) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::OutFilterMap' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, FilterMap) == 0x000050, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::FilterMap' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, K2Node_MakeStruct_DMSearchSetting) == 0x0000A0, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::K2Node_MakeStruct_DMSearchSetting' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Key) == 0x0000B8, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Key' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Value) == 0x0000C0, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Value' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, Temp_name_Variable) == 0x0000D0, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_Conv_TextToString_ReturnValue) == 0x0000D8, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, K2Node_MakeStruct_DMSearchSetting_1) == 0x0000E8, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::K2Node_MakeStruct_DMSearchSetting_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Key_1) == 0x000100, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Key_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Value_1) == 0x000108, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Value_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_Conv_TextToString_ReturnValue_1) == 0x000118, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, K2Node_MakeStruct_DMSearchSetting_2) == 0x000128, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::K2Node_MakeStruct_DMSearchSetting_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_MakeLiteralByte_ReturnValue) == 0x000140, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, K2Node_MakeStruct_DMSearchSetting_3) == 0x000148, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::K2Node_MakeStruct_DMSearchSetting_3' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_Conv_ByteToString_ReturnValue) == 0x000160, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_Conv_ByteToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, K2Node_MakeStruct_DMSearchSetting_4) == 0x000170, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::K2Node_MakeStruct_DMSearchSetting_4' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, Temp_name_Variable_1) == 0x000188, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetValue_ReturnValue) == 0x000190, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Key_2) == 0x000194, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Key_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Value_2) == 0x0001A0, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Value_2' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, K2Node_MakeStruct_DMSearchSetting_5) == 0x0001B0, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::K2Node_MakeStruct_DMSearchSetting_5' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetValue_ReturnValue_1) == 0x0001C8, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Key_3) == 0x0001CC, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Key_3' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BuildFilter, CallFunc_GetFilter_Value_3) == 0x0001D8, "Member 'Widget_CommonSessionBrowser_C_BuildFilter::CallFunc_GetFilter_Value_3' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature) == 0x000010, "Wrong size on Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature, Text) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MinPlayers_Filter_K2Node_ComponentBoundEvent_7_OnFilterChanged__DelegateSignature::Text' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature) == 0x000010, "Wrong size on Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature, Text) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_MaxPlayers_Filter_K2Node_ComponentBoundEvent_8_OnFilterChanged__DelegateSignature::Text' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature final
{
public:
	class UObject*                                Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            Widget;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature) == 0x000010, "Wrong size on Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature, Item) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature::Item' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature, Widget) == 0x000008, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_SessionBrowser_Fix_SessionList_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature::Widget' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Refresh_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BndEvt__Widget_CommonSessionBrowser_W_Button_Back_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function Widget_CommonSessionBrowser.Widget_CommonSessionBrowser_C.BP_GetDesiredFocusTarget
// 0x0040 (0x0040 - 0x0000)
struct Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetDisplayedEntryWidgets_ReturnValue;     // 0x0008(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget_CommonSessionEntry_C*           K2Node_DynamicCast_AsWidget_Common_Session_Entry;  // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget) == 0x000040, "Wrong size on Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, CallFunc_GetDisplayedEntryWidgets_ReturnValue) == 0x000008, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::CallFunc_GetDisplayedEntryWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000018, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, CallFunc_Array_Get_Item) == 0x000020, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, K2Node_DynamicCast_AsWidget_Common_Session_Entry) == 0x000030, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::K2Node_DynamicCast_AsWidget_Common_Session_Entry' has a wrong offset!");
static_assert(offsetof(Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'Widget_CommonSessionBrowser_C_BP_GetDesiredFocusTarget::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

