#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_DashScreen

#include "Basic.hpp"


namespace SDK::Params
{

// Function Widget_DashScreen.Widget_DashScreen_C.ExecuteUbergraph_Widget_DashScreen
// 0x00A0 (0x00A0 - 0x0000)
struct Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARGamePlayerController*                 K2Node_DynamicCast_AsRGame_Player_Controller;      // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARPlayerPawn*                           K2Node_DynamicCast_AsRPlayer_Pawn;                 // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URGScript*                              K2Node_CustomEvent_AbilityScript;                  // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsObjectASoftClass_ReturnValue;           // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsObjectChildOfSoftClass_ReturnValue;     // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6B[0x1];                                       // 0x006B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class URGScript* AbilityScript)> K2Node_CreateDelegate_OutputDelegate_2;          // 0x006C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool* RetValue)>               K2Node_CreateDelegate_OutputDelegate_3;            // 0x007C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFCInvokeBlueprintProxy*                CallFunc_CreateInvokeProxyObject_ReturnValue;      // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen) == 0x000008, "Wrong alignment on Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen");
static_assert(sizeof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen) == 0x0000A0, "Wrong size on Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, EntryPoint) == 0x000000, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_GetOwningPlayerPawn_ReturnValue) == 0x000028, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_GetOwningPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_GetController_ReturnValue) == 0x000030, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_DynamicCast_AsRGame_Player_Controller) == 0x000038, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_DynamicCast_AsRGame_Player_Controller' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_DynamicCast_AsRPlayer_Pawn) == 0x000048, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_DynamicCast_AsRPlayer_Pawn' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_CustomEvent_AbilityScript) == 0x000058, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_CustomEvent_AbilityScript' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_PlayAnimationForward_ReturnValue) == 0x000060, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_IsObjectASoftClass_ReturnValue) == 0x000068, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_IsObjectASoftClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_IsObjectChildOfSoftClass_ReturnValue) == 0x000069, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_IsObjectChildOfSoftClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_BooleanOR_ReturnValue) == 0x00006A, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_CreateDelegate_OutputDelegate_2) == 0x00006C, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, K2Node_CreateDelegate_OutputDelegate_3) == 0x00007C, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_CreateInvokeProxyObject_ReturnValue) == 0x000090, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_CreateInvokeProxyObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen, CallFunc_IsValid_ReturnValue) == 0x000098, "Member 'Widget_DashScreen_C_ExecuteUbergraph_Widget_DashScreen::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function Widget_DashScreen.Widget_DashScreen_C.IsCharacterScriptValid
// 0x0020 (0x0020 - 0x0000)
struct Widget_DashScreen_C_IsCharacterScriptValid final
{
public:
	bool                                          Valid;                                             // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARPlayerPawn*                           K2Node_DynamicCast_AsRPlayer_Pawn;                 // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DashScreen_C_IsCharacterScriptValid) == 0x000008, "Wrong alignment on Widget_DashScreen_C_IsCharacterScriptValid");
static_assert(sizeof(Widget_DashScreen_C_IsCharacterScriptValid) == 0x000020, "Wrong size on Widget_DashScreen_C_IsCharacterScriptValid");
static_assert(offsetof(Widget_DashScreen_C_IsCharacterScriptValid, Valid) == 0x000000, "Member 'Widget_DashScreen_C_IsCharacterScriptValid::Valid' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_IsCharacterScriptValid, CallFunc_GetOwningPlayerPawn_ReturnValue) == 0x000008, "Member 'Widget_DashScreen_C_IsCharacterScriptValid::CallFunc_GetOwningPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_IsCharacterScriptValid, K2Node_DynamicCast_AsRPlayer_Pawn) == 0x000010, "Member 'Widget_DashScreen_C_IsCharacterScriptValid::K2Node_DynamicCast_AsRPlayer_Pawn' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_IsCharacterScriptValid, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'Widget_DashScreen_C_IsCharacterScriptValid::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Widget_DashScreen_C_IsCharacterScriptValid, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'Widget_DashScreen_C_IsCharacterScriptValid::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function Widget_DashScreen.Widget_DashScreen_C.OnDashed
// 0x0008 (0x0008 - 0x0000)
struct Widget_DashScreen_C_OnDashed final
{
public:
	class URGScript*                              AbilityScript;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Widget_DashScreen_C_OnDashed) == 0x000008, "Wrong alignment on Widget_DashScreen_C_OnDashed");
static_assert(sizeof(Widget_DashScreen_C_OnDashed) == 0x000008, "Wrong size on Widget_DashScreen_C_OnDashed");
static_assert(offsetof(Widget_DashScreen_C_OnDashed, AbilityScript) == 0x000000, "Member 'Widget_DashScreen_C_OnDashed::AbilityScript' has a wrong offset!");

}

