#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_CosmeticEntryContentBase

#include "Basic.hpp"

#include "Widget_CosmeticEntryContentBase_classes.hpp"
#include "Widget_CosmeticEntryContentBase_parameters.hpp"


namespace SDK
{

// Function Widget_CosmeticEntryContentBase.Widget_CosmeticEntryContentBase_C.SetContentInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPlayerCosmeticOption&     CosmeticOptionData                                     (BlueprintVisible, BlueprintReadOnly, Parm)

void UWidget_CosmeticEntryContentBase_C::SetContentInfo(const struct FPlayerCosmeticOption& CosmeticOptionData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CosmeticEntryContentBase_C", "SetContentInfo");

	Params::Widget_CosmeticEntryContentBase_C_SetContentInfo Parms{};

	Parms.CosmeticOptionData = std::move(CosmeticOptionData);

	UObject::ProcessEvent(Func, &Parms);
}

}

